services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heroesascent
    restart: always
    ports:
      - "80:10000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=heroesascent
      - DB_USERNAME=heroes
      - DB_PASSWORD=GL5nK:^P>UgG%2
    depends_on:
      - db
    volumes:
      - /root/HeroesAscentServer:/var/www/html


  db:
    image: mysql:8.0
    container_name: heroesascent_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heroesascent
      MYSQL_USER: heroes
      MYSQL_PASSWORD: GL5nK:^P>UgG%2
    volumes:
      # Percorso persistente reale sul server (non volume Docker)
      - /srv/docker/mysql/heroesascent:/var/lib/mysql
    ports:
      - "3306:3306"